---
title: Bloom Publishing
timezone: Australia/Melbourne
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  store:
    title: Store
    output: true
  uploads:
    title: Uploads
    output: true
author: Bloom
email: info@bloompublishing.com.au
description: 'Bloom is an independent publishing house based in Melbourne, Australia.

'
permalink: pretty
exclude:
- Gemfile.lock
- Gemfile
- README*
- node_modules
- ".gitignore"
- assets/scripts/src
- yarn.lock
- ".git"
- package.json
- package-lock.json
facebook_url: https://www.facebook.com/bloompublishing
insta_url: https://www.instagram.com/bloompublishing
whitelist:
- jekyll-redirect-from
